SAUCE TOMATES AU POULET BRAISE AUX LEGUMES + COUSCOUS,	COUSCOUS  GRAS + VIANDE DE MOUTON,	COUSCOUS  BLANC  + VIANDE DE MOUTON,
PIRON,	AKASSA,	EBA,
PATE DE MAÏS,	DAKOUIN,
	BROCHETTE DE GESIER+ IGNAME BOUILLIE,


RIZ + HARICOT ET FRITURE D’ESCARGOT,
	FRITURE D’ESCARGOT + SAUCE CRINCRIN + PATE DE TELIBO,
	FRITURE VIANDE DE BŒUF + SAUCE CRINCRIN + PATE DE TELIBO,

HARICOT BLANC AU MOUTON ET LEGUMES + PAIN OU GARI,
	VIANDE MOUTON + AKASSA OU PIRON + PIMENT ROUGE,
	SAUCE NOIX DE PALME + VIANDE + FROMAGE,


SAUCE LEGUME TCHAYO A L’HUILE D’ARACHIDE AU POISSON FUME + AKASSA,
	
ABOBO + FRITURES+ GARI OU PAIN,
	
ŒUF BROUILLES,


POISSON PANE,
	
BOULETTES DE VIANDE,
	
SANDWICH AU POISSON,

SANDWICH A LA VIANDE,	
SANDWICH A L’AVOCAT	,
BOULETTES DE POISSON,


PATE,
	
SANDWICH AU POULET	,
SAUCE LEGUME AMANVIVEA L’HUILE D’ARACHIDE AU POISSON FUME + AKASSA,

VANZOU AUX GESIERS + PAIN OU GARI,
	
BROCHETTES D’ESCARGOT AU RIZ,
	
TELIBO,

MONYO AU POISSON,	
SAUCE TOMATES AU POULET BRAISE AUX LEGUMES +RIZ	,
SAUCE ASSROKOUI + EBA,

ATTIEKE AU POISSON + ALOCO,
	
POISSON  BRAISE	,
SAUCE CRINCRIN + TELIBO,


JUS DE TAMARIN,
	
ATASSI + VIANDE DE MOUTON + FRITURE,
	
DEGUE MIL,


WASSA-WASSA + POISSON + FRITURE,	
BOUILLIE DE MIL,
	
THE AU LAURIER,


THE A LA MENTHE ET CITRONNELLE	,
OMELETTES ROYALE	,
PATATE DOUCE FRITE ET BEIGNET D’HARICOT,

GLACE AU TOFFEE ,TCHAPALO		
